plugins:
  - serverless-dotenv-plugin
  - serverless-domain-manager

custom:
  customDomain:
    domainName: samp-api.brz.gg
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: samp-api.brz.gg

service: samp-api
useDotenv: true
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  memorySize: 128
  iam:
    role: arn:aws:iam::408356563302:role/brz_lambda
package:
  # Directories and files to include in the deployed package
  patterns:
    - dist/**
    - node_modules
    - package.json
    - yarn.lock
functions:
  app:
    handler: dist/app.handler
    events: 
      - http: 
          path: /download
          method: GET
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true