plugins:
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-offline

custom:
  customDomain:
    domainName: samp-api.brz.gg
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: samp-api.brz.gg

service: samp-api
useDotenv: true
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  memorySize: 128
  iam:
    role: arn:aws:iam::408356563302:role/brz_lambda
package:
  # Directories and files to include in the deployed package
  excludeDevDependencies: true
  patterns:
    - dist/**
    - package.json
    - yarn.lock
    - '!.cicd/**'
    - '!src/**'
    - '!terraform/**'
    - '!test/**'
functions:
  app:
    handler: dist/lambda.handler
    events:
     - http:
         method: any
         path: /{any+}
         cors:
            origins: 
              - https://blog.brz.gg
              - https://brz.gg
              - https://samp-api.brz.gg