plugins:
  - serverless-dotenv-plugin

service: samp-api
useDotenv: true
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  memorySize: 128
  iam:
    role: arn:aws:iam::402559046161:role/brz_lambda
package:
  # Directories and files to include in the deployed package
  patterns:
    - dist/**
    - node_modules
    - package.json
    - yarn.lock
functions:
  app:
    handler: dist/app.handler
    events: 
      - http: 
          path: /download
          method: POST
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true