app: notifications
plugins:
  - serverless-dotenv-plugin
  - serverless-domain-manager
  - serverless-offline

custom:
  customDomain:
    domainName: notifications.brz.gg
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
    certificateName: notifications.brz.gg

service: notifications
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  memorySize: 128
  iam:
    role: arn:aws:iam::408356563302:role/brz_lambda
package:
  excludeDevDependencies: true
  patterns:
    - dist/**
    - package.json
    - package-lock.lock
    - '!.cicd/**'
    - '!src/**'
    - '!test/**'
functions:
  app:
    handler: dist/lambda.handler
    events:
     - http:
         method: any
         path: /{any+}