name: test coverage
on:
  workflow_run:
    workflows: ["website-api ci"]
  push:
    branches:
      - main
    paths:
      - '.github/workflows/coverage.yml'
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '18'
    - run: npm install -g yarn
    - run: yarn
    - uses: paambaati/codeclimate-action@v4.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: yarn test:cov