name: notifications ci

run-name: Running notifications CI by @${{ github.actor }}

on:
  push:
    branches:
      - main
    paths:
      - 'apps/notifications/**'
  pull_request:
    paths:
      - '!*.MD'
      - 'apps/notifications/**'
jobs:
  test:
    env:
      working_path: apps/notifications
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node: [ '18' ]
    name: test/node ${{ matrix.node }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g yarn
        working-directory: ${{ env.working_path }}
      - run: yarn install
        working-directory: ${{ env.working_path }}
      - name: run tests & report coverage
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test:cov
          workingDirectory: ${{ env.working_path }}