name: Palworld Start
on: 
  workflow_dispatch:
jobs:
  start_server:
    runs-on: ubuntu-latest
    outputs:
        server_ip_address: ${{ steps.get_ip_address.outputs.stdout }}
    steps:
      - name: Clone the repository code
        uses: actions/checkout@v2
      - name: Setup the Terraform CLI
        uses: hashicorp/setup-terraform@v2
      - name: Setup AWS Credentials
        run: |
          mkdir ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          AWS_PROFILE=default && echo AWS_PROFILE=$AWS_PROFILE >> $GITHUB_ENV
      - name: Initialize the Terraform working directory
        working-directory: apps/palworld/.cicd/terraform
        id: init
        run: terraform init -input=false
      - name: get server ip address
        working-directory: apps/palworld/.cicd/terraform
        id: get_ip_address
        run: terraform output --raw palworld_ip_address
      - name: get server instance id
        working-directory: apps/palworld/.cicd/terraform
        id: get_instance_id
        run: terraform output --raw palworld_instance_id
      - name: start server
        run: |
          aws ec2 start-instances --instance-ids ${{ steps.get_instance_id.outputs.stdout }} --region sa-east-1
  notify:
    needs: start_server
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ vars.PALWORLD_WEBHOOK_ID }}
          webhook_token: ${{ vars.PALWORLD_WEBHOOK_TOKEN }}
          args: "Atenção! o Pal foi iniciado (DNS: pal.brz.gg:8211, IP estático ${{ needs.terraform.outputs.server_ip_address }}:8211)."